use_frameworks!

platform :ios, '9.0'

target 'ZTErrorOrNoDataView_Example' do
  pod 'ZTErrorOrNoDataView', :path => '../'

  target 'ZTErrorOrNoDataView_Tests' do
    inherit! :search_paths

    
  end
end
